import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import Layout from "@/components/Layout";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { toast } from "sonner";
import { Plus, CheckCircle, Clock, Home, User, Calendar, Sparkles, ChevronDown, ChevronRight, CalendarDays, Users, ClipboardList } from "lucide-react";

const API = process.env.REACT_APP_BACKEND_URL;

const TASK_TYPES = [
  { value: "cleaning", label: "Cleaning", icon: "🧹", color: "bg-blue-500" },
  { value: "check_in", label: "Check-in", icon: "🔑", color: "bg-emerald-500" },
  { value: "check_out", label: "Check-out", icon: "🚪", color: "bg-purple-500" },
  { value: "maintenance", label: "Maintenance", icon: "🛠", color: "bg-amber-500" },
  { value: "transport", label: "Transport", icon: "🚗", color: "bg-cyan-500" },
  { value: "breakfast", label: "Breakfast", icon: "🍳", color: "bg-orange-500" },
  { value: "meal", label: "Meal", icon: "🍽", color: "bg-rose-500" },
  { value: "excursion", label: "Excursion", icon: "🏖", color: "bg-indigo-500" },
  { value: "other", label: "Other", icon: "📋", color: "bg-gray-500" },
];

const PRIORITIES = [
  { value: "high", label: "High", color: "bg-red-500/10 text-red-600 border-red-200" },
  { value: "medium", label: "Medium", color: "bg-amber-500/10 text-amber-600 border-amber-200" },
  { value: "low", label: "Low", color: "bg-gray-500/10 text-gray-600 border-gray-200" },
];

const empty = {
  task_type: "",
  custom_type: "",
  property_id: "",
  assigned_staff_id: "",
  due_date: new Date().toISOString().slice(0, 10),
  priority: "medium",
  notes: "",
};

// Expandable Task Card Component
function TaskCard({ task, properties, team, bookings, onComplete, onEdit, index = 0 }) {
  const [expanded, setExpanded] = useState(false);
  const typeConfig = TASK_TYPES.find(t => t.value === task.task_type) || TASK_TYPES[8];
  const priorityConfig = PRIORITIES.find(p => p.value === task.priority) || PRIORITIES[1];
  const property = properties.find(p => p.id === task.property_id);
  const assignee = team.find(s => s.id === task.assigned_staff_id);
  const booking = bookings.find(b => b.id === task.booking_id);
  const isAutoGenerated = task.auto_generated;
  
  return (
    <Collapsible open={expanded} onOpenChange={setExpanded}>
      <div 
        className={`bg-white dark:bg-gray-800/50 border border-gray-100 dark:border-gray-700/50 rounded-xl hover:shadow-md transition-all animate-fade-in opacity-0 ${task.status === 'completed' ? 'opacity-60' : ''}`}
        style={{ animationDelay: `${0.05 + index * 0.03}s` }}
      >
        {/* Main Row */}
        <div className="p-4">
          <div className="flex items-start gap-3">
            <Checkbox 
              checked={task.status === "completed"}
              onCheckedChange={() => onComplete(task)}
              className="mt-1"
              data-testid={`task-checkbox-${task.id}`}
            />
            
            <div className="flex-1 min-w-0">
              {/* Primary Info */}
              <div className="flex items-center gap-2 mb-2">
                <span className="text-lg">{typeConfig.icon}</span>
                <span className={`font-medium ${task.status === 'completed' ? 'line-through text-muted-foreground' : ''}`}>
                  {typeConfig.label}
                  {task.task_type === 'other' && task.custom_type && `: ${task.custom_type}`}
                </span>
                {isAutoGenerated && (
                  <Badge variant="outline" className="text-[10px] bg-primary/5 text-primary border-primary/20">
                    <Sparkles className="h-3 w-3 mr-1" />Auto
                  </Badge>
                )}
                <Badge variant="outline" className={`text-[10px] ml-auto ${priorityConfig.color}`}>
                  {priorityConfig.label}
                </Badge>
              </div>
              
              {/* Secondary Info - Always Visible */}
              <div className="flex flex-wrap items-center gap-x-4 gap-y-1.5 text-sm text-muted-foreground">
                <span className="flex items-center gap-1.5">
                  <CalendarDays className="h-3.5 w-3.5" />
                  {task.due_date}
                </span>
                {property && (
                  <span className="flex items-center gap-1.5">
                    <Home className="h-3.5 w-3.5" />{property.name}
                  </span>
                )}
                {assignee && (
                  <span className="flex items-center gap-1.5">
                    <User className="h-3.5 w-3.5" />{assignee.first_name} {assignee.last_name}
                  </span>
                )}
                {booking && (
                  <span className="flex items-center gap-1.5 text-primary">
                    <ClipboardList className="h-3.5 w-3.5" />
                    {booking.guest_name || 'Guest'} ({booking.check_in} - {booking.check_out})
                  </span>
                )}
              </div>
            </div>
            
            {/* Expand Button */}
            <CollapsibleTrigger asChild>
              <Button variant="ghost" size="icon" className="h-8 w-8 shrink-0">
                {expanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
              </Button>
            </CollapsibleTrigger>
          </div>
        </div>
        
        {/* Expanded Details */}
        <CollapsibleContent>
          <div className="px-4 pb-4 pt-0 border-t border-gray-100 dark:border-gray-700/50 mt-0">
            <div className="pt-3 grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
              {/* Booking Details */}
              {booking && (
                <div className="space-y-2 bg-muted/30 rounded-lg p-3">
                  <p className="font-medium text-xs uppercase text-muted-foreground">Booking Details</p>
                  <div className="space-y-1">
                    <p><span className="text-muted-foreground">Guest:</span> {booking.guest_name || 'N/A'}</p>
                    <p><span className="text-muted-foreground">Check-in:</span> {booking.check_in}</p>
                    <p><span className="text-muted-foreground">Check-out:</span> {booking.check_out}</p>
                    <p><span className="text-muted-foreground">Guests:</span> {booking.guests_count || 'N/A'}</p>
                    <p><span className="text-muted-foreground">Source:</span> {booking.ota_source || 'Manual'}</p>
                  </div>
                </div>
              )}
              
              {/* Task Notes */}
              <div className="space-y-2 bg-muted/30 rounded-lg p-3">
                <p className="font-medium text-xs uppercase text-muted-foreground">Task Notes</p>
                <p className="text-muted-foreground">
                  {task.description || task.notes || 'No notes added'}
                </p>
                {task.created_at && (
                  <p className="text-xs text-muted-foreground mt-2">
                    Created: {new Date(task.created_at).toLocaleDateString()}
                  </p>
                )}
              </div>
            </div>
          </div>
        </CollapsibleContent>
      </div>
    </Collapsible>
  );
}

// Filter Card Component - Clickable
function FilterCard({ icon, label, count, color, bgColor, isActive, onClick }) {
  return (
    <Card 
      className={`cursor-pointer transition-all hover:shadow-md ${bgColor} ${isActive ? 'ring-2 ring-primary ring-offset-2' : ''}`}
      onClick={onClick}
      data-testid={`filter-${label.toLowerCase()}`}
    >
      <CardContent className="p-4 flex items-center gap-3">
        <span className="text-2xl">{icon}</span>
        <div>
          <p className={`text-xs font-medium ${color}`}>{label}</p>
          <p className={`text-xl font-bold ${color.replace('/10', '').replace('text-', 'text-')}`}>{count}</p>
        </div>
        {isActive && <CheckCircle className="h-4 w-4 ml-auto text-primary" />}
      </CardContent>
    </Card>
  );
}

export default function Operations() {
  const { user, loading: authLoading } = useAuth();
  const navigate = useNavigate();
  const [tasks, setTasks] = useState([]);
  const [properties, setProperties] = useState([]);
  const [team, setTeam] = useState([]);
  const [bookings, setBookings] = useState([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [form, setForm] = useState(empty);
  const [editing, setEditing] = useState(null);
  const [saving, setSaving] = useState(false);
  
  // Default to "today" tab
  const [viewDate, setViewDate] = useState("today");
  // Filter by task type (null = show all)
  const [activeFilter, setActiveFilter] = useState(null);

  useEffect(() => { if (!authLoading && !user) navigate("/"); }, [user, authLoading, navigate]);

  const fetchData = async () => {
    try {
      const [tasksRes, propsRes, teamRes, bookingsRes] = await Promise.all([
        fetch(`${API}/api/tasks`, { credentials: "include" }),
        fetch(`${API}/api/properties`, { credentials: "include" }),
        fetch(`${API}/api/staff`, { credentials: "include" }).catch(() => ({ ok: false })),
        fetch(`${API}/api/bookings`, { credentials: "include" }).catch(() => ({ ok: false })),
      ]);
      
      if (tasksRes.ok) setTasks(await tasksRes.json());
      if (propsRes.ok) setProperties(await propsRes.json());
      if (teamRes.ok) setTeam(await teamRes.json());
      if (bookingsRes.ok) setBookings(await bookingsRes.json());
    } catch (err) { console.error(err); } finally { setLoading(false); }
  };

  useEffect(() => { if (user?.company_id) fetchData(); }, [user]); // eslint-disable-line

  const handleSave = async () => {
    if (!form.task_type) { toast.error("Please select a task type"); return; }
    if (!form.property_id) { toast.error("Please select a property"); return; }
    if (form.task_type === "other" && !form.custom_type?.trim()) { 
      toast.error("Please enter a custom task name"); return; 
    }
    
    setSaving(true);
    try {
      const method = editing ? "PUT" : "POST";
      const url = editing ? `${API}/api/tasks/${editing}` : `${API}/api/tasks`;
      
      const typeConfig = TASK_TYPES.find(t => t.value === form.task_type);
      const title = form.task_type === "other" ? form.custom_type : typeConfig?.label || form.task_type;
      
      const body = {
        title,
        task_type: form.task_type,
        custom_type: form.task_type === "other" ? form.custom_type : null,
        property_id: form.property_id,
        assigned_staff_id: form.assigned_staff_id || null,
        due_date: form.due_date,
        priority: form.priority,
        description: form.notes,
        status: "pending",
      };
      
      const res = await fetch(url, { 
        method, 
        headers: { "Content-Type": "application/json" }, 
        credentials: "include", 
        body: JSON.stringify(body) 
      });
      
      if (res.ok) {
        toast.success(editing ? "Task updated" : "Task created");
        setDialogOpen(false);
        setForm(empty);
        setEditing(null);
        fetchData();
      } else {
        const err = await res.json();
        toast.error(err.detail || "Failed to save task");
      }
    } catch (err) { toast.error("Error saving task"); } finally { setSaving(false); }
  };

  const handleComplete = async (task) => {
    const newStatus = task.status === "completed" ? "pending" : "completed";
    try {
      const res = await fetch(`${API}/api/tasks/${task.id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ status: newStatus }),
      });
      if (res.ok) {
        toast.success(newStatus === "completed" ? "Task completed!" : "Task reopened");
        fetchData();
      }
    } catch (err) { toast.error("Error updating task"); }
  };

  const openEdit = (task) => {
    setForm({
      task_type: task.task_type,
      custom_type: task.custom_type || "",
      property_id: task.property_id,
      assigned_staff_id: task.assigned_staff_id || "",
      due_date: task.due_date,
      priority: task.priority,
      notes: task.description || "",
    });
    setEditing(task.id);
    setDialogOpen(true);
  };

  if (authLoading || !user) {
    return (
      <div className="h-screen flex items-center justify-center bg-background">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
      </div>
    );
  }

  const isAdmin = user?.role === "company_admin";
  const set = (k, v) => setForm(p => ({ ...p, [k]: v }));
  
  // Date calculations
  const today = new Date().toISOString().slice(0, 10);
  const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
  
  // Step 1: Filter by date
  let dateFilteredTasks = tasks;
  if (viewDate === "today") {
    dateFilteredTasks = tasks.filter(t => t.due_date === today);
  } else if (viewDate === "tomorrow") {
    dateFilteredTasks = tasks.filter(t => t.due_date === tomorrow);
  } else if (viewDate === "upcoming") {
    dateFilteredTasks = tasks.filter(t => t.due_date > today && t.status !== "completed");
  }
  
  // Counts for filter cards (based on date filter)
  const cleaningsCount = dateFilteredTasks.filter(t => t.task_type === "cleaning" && t.status !== "completed").length;
  const checkInsCount = dateFilteredTasks.filter(t => t.task_type === "check_in" && t.status !== "completed").length;
  const checkOutsCount = dateFilteredTasks.filter(t => t.task_type === "check_out" && t.status !== "completed").length;
  const completedCount = dateFilteredTasks.filter(t => t.status === "completed").length;
  
  // Step 2: Apply type/status filter
  let filteredTasks = dateFilteredTasks;
  if (activeFilter === "cleaning") {
    filteredTasks = dateFilteredTasks.filter(t => t.task_type === "cleaning" && t.status !== "completed");
  } else if (activeFilter === "check_in") {
    filteredTasks = dateFilteredTasks.filter(t => t.task_type === "check_in" && t.status !== "completed");
  } else if (activeFilter === "check_out") {
    filteredTasks = dateFilteredTasks.filter(t => t.task_type === "check_out" && t.status !== "completed");
  } else if (activeFilter === "completed") {
    filteredTasks = dateFilteredTasks.filter(t => t.status === "completed");
  }
  
  // Group tasks for display when no filter is active
  const pendingTasks = filteredTasks.filter(t => t.status !== "completed");
  const completedTasks = filteredTasks.filter(t => t.status === "completed");
  
  // Toggle filter (click same = deactivate)
  const toggleFilter = (filter) => {
    setActiveFilter(prev => prev === filter ? null : filter);
  };
  
  // Pending count for subtitle
  const pendingToday = tasks.filter(t => t.due_date === today && t.status !== "completed").length;

  return (
    <Layout>
      <div className="space-y-6 max-w-[1200px] mx-auto" data-testid="operations-page">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 animate-fade-in">
          <div>
            <h1 className="font-heading text-2xl font-bold text-foreground">Operations</h1>
            <p className="text-sm text-muted-foreground mt-1">
              {pendingToday > 0 ? `${pendingToday} tasks pending today` : "All caught up for today!"}
            </p>
          </div>
          <div className="flex items-center gap-2">
            {/* Date View Selector */}
            <div className="flex items-center rounded-lg border bg-muted/30 p-0.5">
              {["today", "tomorrow", "upcoming", "all"].map(v => (
                <Button 
                  key={v}
                  variant={viewDate === v ? "default" : "ghost"} 
                  size="sm" 
                  className="h-8 px-3 capitalize"
                  onClick={() => { setViewDate(v); setActiveFilter(null); }}
                  data-testid={`date-filter-${v}`}
                >
                  {v}
                </Button>
              ))}
            </div>
            
            {isAdmin && (
              <Button onClick={() => { setForm(empty); setEditing(null); setDialogOpen(true); }} data-testid="add-task-btn" className="shadow-sm">
                <Plus className="mr-2 h-4 w-4" />Add Task
              </Button>
            )}
          </div>
        </div>

        {/* Filter Cards - Clickable */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <FilterCard 
            icon="🧹" 
            label="Cleanings" 
            count={cleaningsCount}
            color="text-blue-600 dark:text-blue-400"
            bgColor="bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800"
            isActive={activeFilter === "cleaning"}
            onClick={() => toggleFilter("cleaning")}
          />
          <FilterCard 
            icon="🔑" 
            label="Check-ins" 
            count={checkInsCount}
            color="text-emerald-600 dark:text-emerald-400"
            bgColor="bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-800"
            isActive={activeFilter === "check_in"}
            onClick={() => toggleFilter("check_in")}
          />
          <FilterCard 
            icon="🚪" 
            label="Check-outs" 
            count={checkOutsCount}
            color="text-purple-600 dark:text-purple-400"
            bgColor="bg-purple-50 dark:bg-purple-900/20 border-purple-200 dark:border-purple-800"
            isActive={activeFilter === "check_out"}
            onClick={() => toggleFilter("check_out")}
          />
          <FilterCard 
            icon="✓" 
            label="Completed" 
            count={completedCount}
            color="text-gray-600 dark:text-gray-400"
            bgColor="bg-gray-50 dark:bg-gray-800/50 border-gray-200 dark:border-gray-700"
            isActive={activeFilter === "completed"}
            onClick={() => toggleFilter("completed")}
          />
        </div>

        {/* Task List */}
        {loading ? (
          <Card><CardContent className="p-6 h-48 animate-pulse bg-muted" /></Card>
        ) : filteredTasks.length === 0 ? (
          <Card className="border-dashed">
            <CardContent className="p-12 text-center">
              <CheckCircle className="h-12 w-12 mx-auto text-emerald-500 mb-4" />
              <h3 className="font-semibold text-lg mb-2">
                {activeFilter ? `No ${activeFilter.replace('_', '-')} tasks` : "No operations scheduled"}
              </h3>
              <p className="text-muted-foreground mb-6">
                {viewDate === "today" 
                  ? "No operations scheduled for today." 
                  : viewDate === "tomorrow"
                  ? "No operations scheduled for tomorrow."
                  : "No tasks to show for this period."}
              </p>
              <div className="flex items-center justify-center gap-3">
                {viewDate === "today" && (
                  <Button variant="outline" onClick={() => setViewDate("upcoming")} data-testid="view-upcoming-btn">
                    View Upcoming
                  </Button>
                )}
                {isAdmin && (
                  <Button onClick={() => { setForm(empty); setEditing(null); setDialogOpen(true); }} data-testid="add-task-empty-btn">
                    <Plus className="mr-2 h-4 w-4" />Add Task
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-3">
            {/* Show active filter label */}
            {activeFilter && (
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <span>Showing:</span>
                <Badge variant="secondary" className="capitalize">
                  {activeFilter.replace('_', ' ')} tasks
                </Badge>
                <Button variant="ghost" size="sm" className="h-6 px-2 text-xs" onClick={() => setActiveFilter(null)}>
                  Clear filter
                </Button>
              </div>
            )}
            
            {/* Task Cards */}
            {(activeFilter === "completed" ? completedTasks : pendingTasks).map((task, i) => (
              <TaskCard 
                key={task.id} 
                task={task} 
                properties={properties} 
                team={team}
                bookings={bookings}
                onComplete={handleComplete}
                onEdit={openEdit}
                index={i}
              />
            ))}
            
            {/* Show completed section when no filter and there are completed tasks */}
            {!activeFilter && completedTasks.length > 0 && pendingTasks.length > 0 && (
              <div className="pt-4 border-t mt-6">
                <div className="flex items-center gap-2 mb-3">
                  <CheckCircle className="h-4 w-4 text-muted-foreground" />
                  <span className="text-sm font-medium text-muted-foreground">Completed ({completedTasks.length})</span>
                </div>
                {completedTasks.map((task, i) => (
                  <TaskCard 
                    key={task.id} 
                    task={task} 
                    properties={properties} 
                    team={team}
                    bookings={bookings}
                    onComplete={handleComplete}
                    onEdit={openEdit}
                    index={i}
                  />
                ))}
              </div>
            )}
          </div>
        )}

        {/* Add/Edit Task Dialog */}
        <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
          <DialogContent className="sm:max-w-md">
            <DialogHeader>
              <DialogTitle className="font-heading">{editing ? "Edit Task" : "Add Task"}</DialogTitle>
              <DialogDescription>
                {editing ? "Update task details" : "Create a new task"}
              </DialogDescription>
            </DialogHeader>
            <div className="grid gap-4 py-2">
              <div className="space-y-2">
                <Label>Task Type *</Label>
                <Select value={form.task_type} onValueChange={v => set("task_type", v)}>
                  <SelectTrigger data-testid="task-type-select">
                    <SelectValue placeholder="Select type..." />
                  </SelectTrigger>
                  <SelectContent>
                    {TASK_TYPES.map(t => (
                      <SelectItem key={t.value} value={t.value}>
                        <span className="flex items-center gap-2">
                          <span>{t.icon}</span>
                          <span>{t.label}</span>
                        </span>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              {form.task_type === "other" && (
                <div className="space-y-2">
                  <Label>Custom Task Name *</Label>
                  <Input 
                    value={form.custom_type} 
                    onChange={e => set("custom_type", e.target.value)} 
                    placeholder="e.g., Pool cleaning, Guest welcome..."
                    data-testid="custom-type-input"
                  />
                </div>
              )}
              
              <div className="space-y-2">
                <Label>Property *</Label>
                <Select value={form.property_id} onValueChange={v => set("property_id", v)}>
                  <SelectTrigger data-testid="task-property-select">
                    <SelectValue placeholder="Select property..." />
                  </SelectTrigger>
                  <SelectContent>
                    {properties.map(p => (
                      <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              <div className="space-y-2">
                <Label>Assign To</Label>
                <Select value={form.assigned_staff_id || "unassigned"} onValueChange={v => set("assigned_staff_id", v === "unassigned" ? "" : v)}>
                  <SelectTrigger data-testid="task-assignee-select">
                    <SelectValue placeholder="Unassigned" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="unassigned">Unassigned</SelectItem>
                    {team.filter(s => s.active).map(s => (
                      <SelectItem key={s.id} value={s.id}>
                        {s.first_name} {s.last_name} ({s.staff_role})
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Date *</Label>
                  <Input 
                    type="date" 
                    value={form.due_date} 
                    onChange={e => set("due_date", e.target.value)}
                    data-testid="task-date-input"
                  />
                </div>
                <div className="space-y-2">
                  <Label>Priority</Label>
                  <Select value={form.priority} onValueChange={v => set("priority", v)}>
                    <SelectTrigger data-testid="task-priority-select">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {PRIORITIES.map(p => (
                        <SelectItem key={p.value} value={p.value}>{p.label}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              
              <div className="space-y-2">
                <Label>Notes (optional)</Label>
                <Textarea 
                  value={form.notes} 
                  onChange={e => set("notes", e.target.value)} 
                  placeholder="Any additional details..."
                  rows={2}
                  data-testid="task-notes-input"
                />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button>
              <Button onClick={handleSave} disabled={saving} data-testid="save-task-btn">
                {saving ? "Saving..." : editing ? "Update" : "Create"}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </Layout>
  );
}
