import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import Layout from "@/components/Layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { toast } from "sonner";
import { Plus, CheckCircle, Clock, Home, User, Calendar, Sparkles, ChevronRight, AlertCircle, RefreshCw } from "lucide-react";

const API = process.env.REACT_APP_BACKEND_URL;

// Task types - simple predefined list
const TASK_TYPES = [
  { value: "cleaning", label: "Cleaning", icon: "🧹", color: "bg-blue-500" },
  { value: "check_in", label: "Check-in", icon: "🔑", color: "bg-emerald-500" },
  { value: "check_out", label: "Check-out", icon: "🚪", color: "bg-purple-500" },
  { value: "maintenance", label: "Maintenance", icon: "🛠", color: "bg-amber-500" },
  { value: "transport", label: "Transport", icon: "🚗", color: "bg-cyan-500" },
  { value: "breakfast", label: "Breakfast", icon: "🍳", color: "bg-orange-500" },
  { value: "meal", label: "Meal", icon: "🍽", color: "bg-rose-500" },
  { value: "excursion", label: "Excursion", icon: "🏖", color: "bg-indigo-500" },
  { value: "other", label: "Other", icon: "📋", color: "bg-gray-500" },
];

const PRIORITIES = [
  { value: "high", label: "High", color: "bg-red-500/10 text-red-600 border-red-200" },
  { value: "medium", label: "Medium", color: "bg-amber-500/10 text-amber-600 border-amber-200" },
  { value: "low", label: "Low", color: "bg-gray-500/10 text-gray-600 border-gray-200" },
];

const empty = {
  task_type: "",
  custom_type: "",
  property_id: "",
  assigned_staff_id: "",
  due_date: new Date().toISOString().slice(0, 10),
  priority: "medium",
  notes: "",
};

// Task Card Component - Clean & Visual
function TaskCard({ task, properties, team, onComplete, onEdit, index = 0 }) {
  const typeConfig = TASK_TYPES.find(t => t.value === task.task_type) || TASK_TYPES[8];
  const priorityConfig = PRIORITIES.find(p => p.value === task.priority) || PRIORITIES[1];
  const property = properties.find(p => p.id === task.property_id);
  const assignee = team.find(s => s.id === task.assigned_staff_id);
  const isAutoGenerated = task.auto_generated;
  
  return (
    <div 
      className={`p-4 bg-white dark:bg-gray-800/50 border border-gray-100 dark:border-gray-700/50 rounded-xl hover:shadow-md transition-all animate-fade-in opacity-0 ${task.status === 'completed' ? 'opacity-60' : ''}`}
      style={{ animationDelay: `${0.05 + index * 0.03}s` }}
    >
      <div className="flex items-start gap-3">
        {/* Checkbox */}
        <Checkbox 
          checked={task.status === "completed"}
          onCheckedChange={() => onComplete(task)}
          className="mt-1"
          data-testid={`task-checkbox-${task.id}`}
        />
        
        {/* Content */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-lg">{typeConfig.icon}</span>
            <span className={`font-medium ${task.status === 'completed' ? 'line-through text-muted-foreground' : ''}`}>
              {typeConfig.label}
              {task.task_type === 'other' && task.custom_type && `: ${task.custom_type}`}
            </span>
            {isAutoGenerated && (
              <Badge variant="outline" className="text-[10px] bg-primary/5 text-primary border-primary/20">
                <Sparkles className="h-3 w-3 mr-1" />Auto
              </Badge>
            )}
          </div>
          
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground">
            {property && (
              <span className="flex items-center gap-1">
                <Home className="h-3 w-3" />{property.name}
              </span>
            )}
            {assignee && (
              <span className="flex items-center gap-1">
                <User className="h-3 w-3" />{assignee.first_name} {assignee.last_name}
              </span>
            )}
          </div>
          
          {task.notes && (
            <p className="text-xs text-muted-foreground mt-2 line-clamp-1">{task.notes}</p>
          )}
        </div>
        
        {/* Priority Badge */}
        <Badge variant="outline" className={`text-[10px] shrink-0 ${priorityConfig.color}`}>
          {priorityConfig.label}
        </Badge>
      </div>
    </div>
  );
}

// Section for grouping tasks
function TaskSection({ title, icon, tasks, properties, team, onComplete, onEdit, emptyMessage, color = "bg-gray-100" }) {
  if (tasks.length === 0) {
    return (
      <div className="p-6 border border-dashed border-gray-200 dark:border-gray-700 rounded-xl text-center">
        <p className="text-sm text-muted-foreground">{emptyMessage}</p>
      </div>
    );
  }
  
  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <div className={`h-8 w-8 rounded-lg ${color} flex items-center justify-center text-lg`}>
          {icon}
        </div>
        <h3 className="font-semibold">{title}</h3>
        <Badge variant="secondary" className="ml-auto">{tasks.length}</Badge>
      </div>
      <div className="space-y-2">
        {tasks.map((task, i) => (
          <TaskCard 
            key={task.id} 
            task={task} 
            properties={properties} 
            team={team}
            onComplete={onComplete}
            onEdit={onEdit}
            index={i}
          />
        ))}
      </div>
    </div>
  );
}

export default function Operations() {
  const { user, loading: authLoading } = useAuth();
  const navigate = useNavigate();
  const [tasks, setTasks] = useState([]);
  const [properties, setProperties] = useState([]);
  const [team, setTeam] = useState([]);
  const [customTypes, setCustomTypes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [form, setForm] = useState(empty);
  const [editing, setEditing] = useState(null);
  const [saving, setSaving] = useState(false);
  const [viewDate, setViewDate] = useState("today");
  const [regenerating, setRegenerating] = useState(false);

  useEffect(() => { if (!authLoading && !user) navigate("/"); }, [user, authLoading, navigate]);

  const fetchData = async () => {
    try {
      const [tasksRes, propsRes, teamRes] = await Promise.all([
        fetch(`${API}/api/tasks`, { credentials: "include" }),
        fetch(`${API}/api/properties`, { credentials: "include" }),
        fetch(`${API}/api/staff`, { credentials: "include" }).catch(() => ({ ok: false })),
      ]);
      
      if (tasksRes.ok) {
        const data = await tasksRes.json();
        setTasks(data);
        // Extract custom task types
        const customs = data
          .filter(t => t.task_type === 'other' && t.custom_type)
          .map(t => t.custom_type);
        setCustomTypes([...new Set(customs)]);
      }
      if (propsRes.ok) setProperties(await propsRes.json());
      if (teamRes.ok) setTeam(await teamRes.json());
    } catch (err) { console.error(err); } finally { setLoading(false); }
  };

  useEffect(() => { if (user?.company_id) fetchData(); }, [user]); // eslint-disable-line

  const handleRegenerateTasks = async () => {
    setRegenerating(true);
    try {
      const res = await fetch(`${API}/api/tasks/regenerate-for-bookings`, {
        method: "POST",
        credentials: "include",
      });
      if (res.ok) {
        const data = await res.json();
        toast.success(data.message || "Tasks regenerated successfully");
        fetchData();
      } else {
        const err = await res.json();
        toast.error(err.detail || "Failed to regenerate tasks");
      }
    } catch (err) {
      toast.error("Error regenerating tasks");
    } finally {
      setRegenerating(false);
    }
  };

  const handleSave = async () => {
    if (!form.task_type) { toast.error("Please select a task type"); return; }
    if (!form.property_id) { toast.error("Please select a property"); return; }
    if (form.task_type === "other" && !form.custom_type?.trim()) { 
      toast.error("Please enter a custom task name"); return; 
    }
    
    setSaving(true);
    try {
      const method = editing ? "PUT" : "POST";
      const url = editing ? `${API}/api/tasks/${editing}` : `${API}/api/tasks`;
      
      // Build title from task type
      const typeConfig = TASK_TYPES.find(t => t.value === form.task_type);
      const title = form.task_type === "other" ? form.custom_type : typeConfig?.label || form.task_type;
      
      const body = {
        title,
        task_type: form.task_type,
        custom_type: form.task_type === "other" ? form.custom_type : null,
        property_id: form.property_id,
        assigned_staff_id: form.assigned_staff_id || null,
        due_date: form.due_date,
        priority: form.priority,
        description: form.notes,
        status: "pending",
      };
      
      const res = await fetch(url, { 
        method, 
        headers: { "Content-Type": "application/json" }, 
        credentials: "include", 
        body: JSON.stringify(body) 
      });
      
      if (res.ok) {
        toast.success(editing ? "Task updated" : "Task created");
        setDialogOpen(false);
        setForm(empty);
        setEditing(null);
        fetchData();
      } else {
        const err = await res.json();
        toast.error(err.detail || "Failed to save task");
      }
    } catch (err) { toast.error("Error saving task"); } finally { setSaving(false); }
  };

  const handleComplete = async (task) => {
    const newStatus = task.status === "completed" ? "pending" : "completed";
    try {
      const res = await fetch(`${API}/api/tasks/${task.id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ status: newStatus }),
      });
      if (res.ok) {
        toast.success(newStatus === "completed" ? "Task completed!" : "Task reopened");
        fetchData();
      }
    } catch (err) { toast.error("Error updating task"); }
  };

  const openEdit = (task) => {
    setForm({
      task_type: task.task_type,
      custom_type: task.custom_type || "",
      property_id: task.property_id,
      assigned_staff_id: task.assigned_staff_id || "",
      due_date: task.due_date,
      priority: task.priority,
      notes: task.description || "",
    });
    setEditing(task.id);
    setDialogOpen(true);
  };

  if (authLoading || !user) {
    return (
      <div className="h-screen flex items-center justify-center bg-background">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
      </div>
    );
  }

  const isAdmin = user?.role === "company_admin";
  const set = (k, v) => setForm(p => ({ ...p, [k]: v }));
  
  // Get today's date
  const today = new Date().toISOString().slice(0, 10);
  const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
  
  // Filter tasks based on view
  let filteredTasks = tasks;
  if (viewDate === "today") {
    filteredTasks = tasks.filter(t => t.due_date === today);
  } else if (viewDate === "tomorrow") {
    filteredTasks = tasks.filter(t => t.due_date === tomorrow);
  } else if (viewDate === "upcoming") {
    filteredTasks = tasks.filter(t => t.due_date > today && t.status !== "completed");
  }
  
  // Group today's tasks by type
  const cleaningsToday = filteredTasks.filter(t => t.task_type === "cleaning" && t.status !== "completed");
  const checkInsToday = filteredTasks.filter(t => t.task_type === "check_in" && t.status !== "completed");
  const checkOutsToday = filteredTasks.filter(t => t.task_type === "check_out" && t.status !== "completed");
  const otherTasks = filteredTasks.filter(t => 
    !["cleaning", "check_in", "check_out"].includes(t.task_type) && t.status !== "completed"
  );
  const completedTasks = filteredTasks.filter(t => t.status === "completed");
  
  // Counts for summary
  const pendingCount = tasks.filter(t => t.due_date === today && t.status !== "completed").length;
  const completedTodayCount = tasks.filter(t => t.due_date === today && t.status === "completed").length;

  // Build task type options including custom types
  const taskTypeOptions = [
    ...TASK_TYPES.slice(0, -1), // All except "other"
    ...customTypes.map(ct => ({ value: `custom_${ct}`, label: ct, icon: "📋", color: "bg-gray-500" })),
    TASK_TYPES[TASK_TYPES.length - 1], // "other" at the end
  ];

  return (
    <Layout>
      <div className="space-y-6 max-w-[1200px] mx-auto" data-testid="operations-page">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 animate-fade-in">
          <div>
            <h1 className="font-heading text-2xl font-bold text-foreground">Operations</h1>
            <p className="text-sm text-muted-foreground mt-1">
              {pendingCount > 0 ? `${pendingCount} tasks pending today` : "All caught up for today!"}
            </p>
          </div>
          <div className="flex items-center gap-2">
            {/* Date View Selector */}
            <div className="flex items-center rounded-lg border bg-muted/30 p-0.5">
              <Button 
                variant={viewDate === "today" ? "default" : "ghost"} 
                size="sm" 
                className="h-8 px-3"
                onClick={() => setViewDate("today")}
              >
                Today
              </Button>
              <Button 
                variant={viewDate === "tomorrow" ? "default" : "ghost"} 
                size="sm" 
                className="h-8 px-3"
                onClick={() => setViewDate("tomorrow")}
              >
                Tomorrow
              </Button>
              <Button 
                variant={viewDate === "upcoming" ? "default" : "ghost"} 
                size="sm" 
                className="h-8 px-3"
                onClick={() => setViewDate("upcoming")}
              >
                Upcoming
              </Button>
              <Button 
                variant={viewDate === "all" ? "default" : "ghost"} 
                size="sm" 
                className="h-8 px-3"
                onClick={() => setViewDate("all")}
              >
                All
              </Button>
            </div>
            
            {isAdmin && (
              <Button onClick={() => { setForm(empty); setEditing(null); setDialogOpen(true); }} data-testid="add-task-btn" className="shadow-sm">
                <Plus className="mr-2 h-4 w-4" />Add Task
              </Button>
            )}
          </div>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <Card className="bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800">
            <CardContent className="p-4 flex items-center gap-3">
              <span className="text-2xl">🧹</span>
              <div>
                <p className="text-xs text-blue-600 dark:text-blue-400 font-medium">Cleanings</p>
                <p className="text-xl font-bold text-blue-700 dark:text-blue-300">{cleaningsToday.length}</p>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-800">
            <CardContent className="p-4 flex items-center gap-3">
              <span className="text-2xl">🔑</span>
              <div>
                <p className="text-xs text-emerald-600 dark:text-emerald-400 font-medium">Check-ins</p>
                <p className="text-xl font-bold text-emerald-700 dark:text-emerald-300">{checkInsToday.length}</p>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-purple-50 dark:bg-purple-900/20 border-purple-200 dark:border-purple-800">
            <CardContent className="p-4 flex items-center gap-3">
              <span className="text-2xl">🚪</span>
              <div>
                <p className="text-xs text-purple-600 dark:text-purple-400 font-medium">Check-outs</p>
                <p className="text-xl font-bold text-purple-700 dark:text-purple-300">{checkOutsToday.length}</p>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-gray-50 dark:bg-gray-800/50 border-gray-200 dark:border-gray-700">
            <CardContent className="p-4 flex items-center gap-3">
              <CheckCircle className="h-6 w-6 text-gray-400" />
              <div>
                <p className="text-xs text-gray-600 dark:text-gray-400 font-medium">Completed</p>
                <p className="text-xl font-bold text-gray-700 dark:text-gray-300">{completedTodayCount}</p>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Task Sections */}
        {loading ? (
          <Card><CardContent className="p-6 h-48 animate-pulse bg-muted" /></Card>
        ) : filteredTasks.length === 0 ? (
          <Card className="border-dashed">
            <CardContent className="p-12 text-center">
              <CheckCircle className="h-12 w-12 mx-auto text-emerald-500 mb-4" />
              <h3 className="font-semibold text-lg mb-2">All Clear!</h3>
              <p className="text-muted-foreground">
                {viewDate === "today" ? "No tasks scheduled for today" : "No tasks to show"}
              </p>
              {isAdmin && (
                <Button className="mt-4" onClick={() => { setForm(empty); setEditing(null); setDialogOpen(true); }}>
                  <Plus className="mr-2 h-4 w-4" />Add Task
                </Button>
              )}
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-6">
            {cleaningsToday.length > 0 && (
              <TaskSection 
                title="Cleanings" 
                icon="🧹" 
                color="bg-blue-100 dark:bg-blue-900/30"
                tasks={cleaningsToday} 
                properties={properties} 
                team={team}
                onComplete={handleComplete}
                onEdit={openEdit}
                emptyMessage="No cleanings today"
              />
            )}
            
            {checkInsToday.length > 0 && (
              <TaskSection 
                title="Check-ins" 
                icon="🔑" 
                color="bg-emerald-100 dark:bg-emerald-900/30"
                tasks={checkInsToday} 
                properties={properties} 
                team={team}
                onComplete={handleComplete}
                onEdit={openEdit}
                emptyMessage="No check-ins today"
              />
            )}
            
            {checkOutsToday.length > 0 && (
              <TaskSection 
                title="Check-outs" 
                icon="🚪" 
                color="bg-purple-100 dark:bg-purple-900/30"
                tasks={checkOutsToday} 
                properties={properties} 
                team={team}
                onComplete={handleComplete}
                onEdit={openEdit}
                emptyMessage="No check-outs today"
              />
            )}
            
            {otherTasks.length > 0 && (
              <TaskSection 
                title="Other Tasks" 
                icon="📋" 
                color="bg-gray-100 dark:bg-gray-800"
                tasks={otherTasks} 
                properties={properties} 
                team={team}
                onComplete={handleComplete}
                onEdit={openEdit}
                emptyMessage="No other tasks"
              />
            )}
            
            {completedTasks.length > 0 && (
              <div className="pt-4 border-t">
                <TaskSection 
                  title="Completed" 
                  icon="✅" 
                  color="bg-gray-100 dark:bg-gray-800"
                  tasks={completedTasks} 
                  properties={properties} 
                  team={team}
                  onComplete={handleComplete}
                  onEdit={openEdit}
                  emptyMessage=""
                />
              </div>
            )}
          </div>
        )}

        {/* Add/Edit Task Dialog - Simplified */}
        <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
          <DialogContent className="sm:max-w-md">
            <DialogHeader>
              <DialogTitle className="font-heading">{editing ? "Edit Task" : "Add Task"}</DialogTitle>
              <DialogDescription>
                {editing ? "Update task details" : "Create a new task"}
              </DialogDescription>
            </DialogHeader>
            <div className="grid gap-4 py-2">
              {/* Task Type - Primary Selection */}
              <div className="space-y-2">
                <Label>Task Type *</Label>
                <Select value={form.task_type} onValueChange={v => set("task_type", v)}>
                  <SelectTrigger data-testid="task-type-select">
                    <SelectValue placeholder="Select type..." />
                  </SelectTrigger>
                  <SelectContent>
                    {TASK_TYPES.map(t => (
                      <SelectItem key={t.value} value={t.value}>
                        <span className="flex items-center gap-2">
                          <span>{t.icon}</span>
                          <span>{t.label}</span>
                        </span>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              {/* Custom Type Name - Only if "Other" selected */}
              {form.task_type === "other" && (
                <div className="space-y-2">
                  <Label>Custom Task Name *</Label>
                  <Input 
                    value={form.custom_type} 
                    onChange={e => set("custom_type", e.target.value)} 
                    placeholder="e.g., Pool cleaning, Guest welcome..."
                    data-testid="custom-type-input"
                  />
                </div>
              )}
              
              {/* Property */}
              <div className="space-y-2">
                <Label>Property *</Label>
                <Select value={form.property_id} onValueChange={v => set("property_id", v)}>
                  <SelectTrigger data-testid="task-property-select">
                    <SelectValue placeholder="Select property..." />
                  </SelectTrigger>
                  <SelectContent>
                    {properties.map(p => (
                      <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              {/* Assigned To */}
              <div className="space-y-2">
                <Label>Assign To</Label>
                <Select value={form.assigned_staff_id || "unassigned"} onValueChange={v => set("assigned_staff_id", v === "unassigned" ? "" : v)}>
                  <SelectTrigger data-testid="task-assignee-select">
                    <SelectValue placeholder="Unassigned" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="unassigned">Unassigned</SelectItem>
                    {team.filter(s => s.active).map(s => (
                      <SelectItem key={s.id} value={s.id}>
                        {s.first_name} {s.last_name} ({s.staff_role})
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              {/* Date & Priority */}
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Date *</Label>
                  <Input 
                    type="date" 
                    value={form.due_date} 
                    onChange={e => set("due_date", e.target.value)}
                    data-testid="task-date-input"
                  />
                </div>
                <div className="space-y-2">
                  <Label>Priority</Label>
                  <Select value={form.priority} onValueChange={v => set("priority", v)}>
                    <SelectTrigger data-testid="task-priority-select">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {PRIORITIES.map(p => (
                        <SelectItem key={p.value} value={p.value}>{p.label}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              
              {/* Notes */}
              <div className="space-y-2">
                <Label>Notes (optional)</Label>
                <Textarea 
                  value={form.notes} 
                  onChange={e => set("notes", e.target.value)} 
                  placeholder="Any additional details..."
                  rows={2}
                  data-testid="task-notes-input"
                />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button>
              <Button onClick={handleSave} disabled={saving} data-testid="save-task-btn">
                {saving ? "Saving..." : editing ? "Update" : "Create"}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </Layout>
  );
}
